[package]
authors = ["Nick Fitzgerald <fitzgen@gmail.com>"]
name = "inlinable_string"
version = "0.1.0"

[dependencies]

[dependencies.clippy]
optional = true
version = "0.0.27"

[features]
nightly = ["clippy"]
